stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

include:
  template: SAST.gitlab-ci.yml

test_python35:
  stage: test
  image: python:3.5
  script:
    - pip install tox
    - tox --skip-missing-interpreters

test_python36:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox --skip-missing-interpreters

test_python37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox --skip-missing-interpreters
